[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20" 
remappings = [
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/v2-periphery/=lib/v2-periphery/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]
via_ir = true
optimizer = true
optimizer_runs = 20

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
